import React from 'react';
import { Download } from 'lucide-react';
import jsPDF from 'jspdf';
import { FDResult, FDInput } from '../utils/calculateFD';

interface DownloadPDFButtonProps {
  result: FDResult;
  input: FDInput;
}

export function DownloadPDFButton({ result, input }: DownloadPDFButtonProps) {
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-IN', {
      style: 'currency',
      currency: 'INR',
      maximumFractionDigits: 0,
    }).format(amount);
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(24);
    doc.setTextColor(59, 130, 246); // Blue color
    doc.text('Fixed Deposit Calculator', 20, 30);
    
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated on ${new Date().toLocaleDateString('en-IN')}`, 20, 40);
    
    // Investment Details
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Investment Details', 20, 60);
    
    doc.setFontSize(12);
    doc.text(`Principal Amount: ${formatCurrency(input.principal)}`, 20, 75);
    doc.text(`Interest Rate: ${input.rate}% per annum`, 20, 85);
    doc.text(`Tenure: ${input.tenure} ${input.tenureUnit}`, 20, 95);
    doc.text(`Compounding: ${input.compounding.charAt(0).toUpperCase() + input.compounding.slice(1).replace('-', ' ')}`, 20, 105);
    
    // Results
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('Calculation Results', 20, 130);
    
    doc.setFontSize(14);
    doc.setTextColor(34, 197, 94); // Green color
    doc.text(`Maturity Amount: ${formatCurrency(result.maturityAmount)}`, 20, 145);
    
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Interest Earned: ${formatCurrency(result.interestEarned)}`, 20, 160);
    doc.text(`Effective Rate: ${result.effectiveRate.toFixed(2)}% per annum`, 20, 170);
    doc.text(`Total Growth: ${result.growth.toFixed(2)}%`, 20, 180);
    
    // Formula explanation
    doc.setFontSize(14);
    doc.text('Formula Used', 20, 205);
    doc.setFontSize(10);
    doc.text('Compound Interest: A = P(1 + r/n)^(nt)', 20, 215);
    doc.text('Where A = Maturity Amount, P = Principal, r = Rate, n = Compounding Frequency, t = Time', 20, 225);
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('This calculation is for illustrative purposes only. Actual returns may vary.', 20, 280);
    doc.text('Generated by FD Calculator - https://bolt.new', 20, 290);
    
    // Save the PDF
    doc.save(`FD_Calculator_${input.principal}_${input.rate}percent_${input.tenure}${input.tenureUnit}.pdf`);
  };

  return (
    <button
      onClick={downloadPDF}
      className="w-full bg-gradient-to-r from-blue-500 to-blue-600 hover:from-blue-600 hover:to-blue-700 text-white font-semibold py-4 px-6 rounded-xl transition-all duration-300 transform hover:scale-[1.02] hover:shadow-lg flex items-center justify-center gap-3"
    >
      <Download className="w-5 h-5" />
      Download PDF Report
    </button>
  );
}